### ISSUE TITLE
Oracle  [desc_tab] and [describe_columns] are not provided in this extension package

### ISSUE THREAD

**Issue by salix2022** [okbob/dbms_sql#3]
Hi ，

I'm using orafce_sql extension, it is found that [desc_tab] and [describe_columns] are not provided in this expansion package.
Is there any reason? I want to migrate these two functions from Oracle to Postgres. What should I do?

I look forward to your reply！
salix

**Comment by okbob** [comment]
po 16. 5. 2022 v 10:20 odesílatel salix2022 ***@***.***>
napsal:

> Hi ，
>
> I'm using orafce_sql extension, it is found that [desc_tab] and
> [describe_columns] are not provided in this expansion package.
> Is there any reason? I want to migrate these two functions from Oracle to
> Postgres. What should I do?
>
There is not any reasons, I wrote this package just against Oracle
documentation, and I never used this package, so I don't know well, what is
common usage. At this moment I cannot say how much work needs to be done.

You can try to implement it, and I'll merge it. Or you can pay me some
developer fee, and I can implement it in the next few weeks.

Regards

Pavel

**Comment by salix2022** [comment]
> po 16. 5. 2022 v 10:20 odesílatel salix2022 ***@***.***> napsal:
> Hi ， I'm using orafce_sql extension, it is found that [desc_tab] and [describe_columns] are not provided in this expansion package. Is there any reason? I want to migrate these two functions from Oracle to Postgres. What should I do?
> There is not any reasons, I wrote this package just against Oracle documentation, and I never used this package, so I don't know well, what is common usage. At this moment I cannot say how much work needs to be done. You can try to implement it, and I'll merge it. Or you can pay me some developer fee, and I can implement it in the next few weeks. Regards Pavel

Hi,Pavel

Thank you for your reply. 
I'm sorry I don't have any extra fee to realize it. 
If I realize it in the future, I will let you merge them into the package.

Thanks!
salix

**Comment by okbob** [comment]
Hi

I implemented dbms_sql.describe_columns - it is available in master branch

Pavel
